### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by emjay73** [nihaomiao/CVPR2023_LFDM#10]
Thank you for sharing the code!

Can you also share the hardware environment required to run this code? (minimum memory requirements, GPU spec.. etc)

**Comment by nihaomiao** [comment]
Hi, @emjay73, I think 24GB should be enough for training with a small batch size according to my preliminary experiments. The released model checkpoints are trained with one A100 (~81GB).

**Comment by emjay73** [comment]
Oh I get it. Thanks!
