### ISSUE TITLE
a demo

### ISSUE THREAD

**Issue by pokameng** [nihaomiao/CVPR2023_LFDM#12]
@nihaomiao 
hello!
When I run python demo/demo_mug.py, the process does not respond.
![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/47957015/87969214-2d0d-409f-afed-9ca99994b81d)

**Comment by nihaomiao** [comment]
same as the issue https://github.com/nihaomiao/CVPR23_LFDM/issues/13#issue-1790952376
