### ISSUE TITLE
demo not running successully

### ISSUE THREAD

**Issue by pokameng** [nihaomiao/CVPR2023_LFDM#13]
@nihaomiao 
hello！
When I run the demo_mug.py， it doesn't run successfully  as follows:
![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/47957015/bb1e3273-97ac-4542-ad87-bd8405bccb2c)

it blocks in this line:
model.sample_one_video(cond_scale=cond_scale)

**Comment by nihaomiao** [comment]
Hi, @pokameng, which error it reports, could you give me more details? Maybe it is just running but needs some time to return the results.
