### ISSUE TITLE
Code of multi gpus training of diffusion model

### ISSUE THREAD

**Issue by ganchaofan0000** [nihaomiao/CVPR2023_LFDM#14]
I want to train the diffusion model with multi gpus. But there are not relevant codes.

**Comment by nihaomiao** [comment]
Hi, @ganchaofan0000, I just add the multi-GPU training codes for MHAD dataset. The training on the other datasets should be similar to MHAD. Please feel free to let me know if you have any other questions.

**Comment by ganchaofan0000** [comment]
Thanks!
