### ISSUE TITLE
about checkpoint

### ISSUE THREAD

**Issue by ymmshi** [nihaomiao/CVPR2023_LFDM#15]
Thanks for your great work! Where can I get the pretrained Taichi/VOX checkpoint? And are the pretrained model very important for LFAE?
<img width="611" alt="image" src="https://github.com/nihaomiao/CVPR23_LFDM/assets/13198991/ce42c309-c100-48ae-9d24-6b3a252f2f33">

**Comment by nihaomiao** [comment]
Hi, @ymmshi, thanks a lot for your interest in our work! We initialize our LFAE with the checkpoint provided in the [github](https://github.com/snap-research/articulated-animation/tree/db2c2135273f601a370e2b62754f9bb56cfd25d5/checkpoints) of MRAA. I think a good initialization will help accelerate the training of LFAE.

**Comment by ymmshi** [comment]
Hi Ni, thanks for your quick reply! It seems the snap's repo is over data quota, and I cannot download the checkpoints. Could you please provide your bak one if there is?
<img width="1404" alt="image" src="https://github.com/nihaomiao/CVPR23_LFDM/assets/13198991/20b048eb-ad15-4098-bdfc-5ce8e968be49">

**Comment by nihaomiao** [comment]
Hi, @ymmshi, this https://github.com/snap-research/articulated-animation/issues/41#issuecomment-901416664 may solve your problem.
