### ISSUE TITLE
 Can image animation be achieved? like  this  demo

### ISSUE THREAD

**Issue by zhanghongyong123456** [nihaomiao/CVPR2023_LFDM#17]
like this demo
https://twitter.com/pika_labs/status/1678892871670464513

**Comment by nihaomiao** [comment]
Hi, @zhanghongyong123456, thanks for your interest! Currently, we only train our model with small datasets and only achieve class-conditioned image-to-video (cI2V) generation. To achieve text-conditioned I2V as the link you show, I think more data and computational resources are required to train a text-to-flow diffusion model.
