### ISSUE TITLE
Where is the pre-trained weight file used when training the model

### ISSUE THREAD

**Issue by Foxerity** [nihaomiao/CVPR2023_LFDM#18]
When I follow your steps to train the model, it reminds me that I need a pre-trained weight file. This problem is in the training code for all three datasets. Where do I get this weights file? Hope to get your reply
`parser.add_argument("--checkpoint",  # use the pretrained Taichi model provided by Snap
                        default="/data/hfn5052/text2motion/RegionMM/taichi256.pth",`

**Comment by lihy715** [comment]
Hi, did you get the weight? I'm trying to do the same thing with you. I'll appreciate if you offer the path to load the taichi256.pth
