### ISSUE TITLE
Hand + Face of Human Pose

### ISSUE THREAD

**Issue by p0mad** [nihaomiao/CVPR2023_LFDM#19]
Hi,
Is it possible to generate a single character from the Pose for about 5 seconds?

I have a video of Pose ( openpose + hands + face) and i was wondering if it is possible to generate an output video withe the length of 5 seconds that has a consistent character/Avatar which plays Dance, .... from the controlled (pose) input?

I have a video of OpenPose+hands+face and i want to generate human like animation (No matter what, but just a consistent Character/Avatar)
[Sample Video](https://github.com/YBYBZhang/ControlVideo/assets/131435526/9062c944-270d-40c0-866b-b72455d58254)

Thanks
Best regards

**Comment by nihaomiao** [comment]
Hi, @p0mad, your task is more similar to pose-guided video generation. For controllable image generation (including pose), ControlNet is quite hot recently ([paper](https://arxiv.org/abs/2302.05543), [code](https://github.com/lllyasviel/ControlNet)). You may be also interested in my previous WACV23 work ([paper](https://arxiv.org/abs/2210.01559), [code](https://github.com/nihaomiao/WACV23_TSNet)), which uses the pose sequence of a driving video and some subject frames to generate a new video.

**Comment by p0mad** [comment]
@nihaomiao 
Thank you so much!
The youtube Dance dataset is not much accurate on hands! while hands are the most important of my project!
best regards

**Comment by p0mad** [comment]
@nihaomiao May i have your contact to talk about implementing an  idea?
Telegram, skype or linkedin

**Comment by nihaomiao** [comment]
Hi, @p0mad, thanks a lot for your interest! But I am busy recently and may not have time to do so. I think there are lots of work about your task. It should not be hard for you to find one, e.g., this CVPR 2022 [paper](https://openaccess.thecvf.com/content/CVPR2022/html/Saunders_Signing_at_Scale_Learning_to_Co-Articulate_Signs_for_Large-Scale_Photo-Realistic_CVPR_2022_paper.html).
