### ISSUE TITLE
demo ModuleNotFoundError

### ISSUE THREAD

**Issue by XiaoHaoPan** [nihaomiao/CVPR2023_LFDM#20]
hello！
When I run the demo_mug.py，it display：

Traceback (most recent call last):
  File "demo/demo_mug.py", line 13, in <module>
    from misc import Logger, grid2fig, conf2fig
ModuleNotFoundError: No module named 'misc'

**Comment by nihaomiao** [comment]
Hi, @XiaoHaoPan, you may need to change the path setting of this [line](https://github.com/nihaomiao/CVPR23_LFDM/blob/bc1ff9a3279921a5d74f6e0b76ea9e505b242bc7/demo/demo_mug.py#L3C1-L3C47).

**Comment by XiaoHaoPan** [comment]
Thank for your help！
