### ISSUE TITLE
NATOPS Dataset preprocessing

### ISSUE THREAD

**Issue by XiaoHaoPan** [nihaomiao/CVPR2023_LFDM#22]
Hi,
I want to train LFDM using NATOPS Dataset,but it(I downloaded it via your link) have a little different in preprocessing,it doesn't have json files.

it like this
![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/127167436/a33c169b-ace8-4544-95fb-9338981e1413)

but this code
![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/127167436/f93c1459-79ba-4d5c-bb9a-d2ce2cae1b7b)

**Comment by nihaomiao** [comment]
Hi, @XiaoHaoPan, thanks for your interest in our work! According to this [line](https://github.com/nihaomiao/CVPR23_LFDM/blob/bc1ff9a3279921a5d74f6e0b76ea9e505b242bc7/preprocessing/preprocess_NATOPS.py#L53) of code, it will create a JSON file and save it to the path `json_path`. So just change `json_path` to where you want to save the JSON file and set  `seg_txt_path` to be the path of downloaded segmentation.txt. This JSON file will be used later.

**Comment by XiaoHaoPan** [comment]
Thank you for your help, the preprocessing process can seem time-consuming.
