### ISSUE TITLE
about memory

### ISSUE THREAD

**Issue by XiaoHaoPan** [nihaomiao/CVPR2023_LFDM#23]
Hi，
How small can the size of the batch_size in the training phase be? At the size you set, I found that my machine didn't have enough video memory, and then I adjusted it to 30 to train.I'm just using a piece of 2080ti (11G)

**Comment by XiaoHaoPan** [comment]
Until now it has happened this problem, it seems to be out of memory, I have 40G of memory.

![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/127167436/a36cefc8-00c7-4ffc-aa34-740a91a47a8e)

Its memory footprint keeps going up and stops at 40.

![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/127167436/08dcd471-7028-4b1a-a477-a554d148dbbc)

**Comment by nihaomiao** [comment]
Hi, @XiaoHaoPan, which module do you train? The stage-one LFAE or stage-two DM?

**Comment by XiaoHaoPan** [comment]
The stage-one LFAE

**Comment by nihaomiao** [comment]
I never had this issue before... Could you try a very small batch size (2 or 4) and see what happens?

**Comment by XiaoHaoPan** [comment]
Thanks for your advice. I'll give it a try.
