### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by XiaoHaoPan** [nihaomiao/CVPR2023_LFDM#24]
When I run python -u DM/train_video_flow_diffusion_natops.py, the whole issue occurs.

It doesn't seem to support versions below 3.8, how to solve this, do you have to reinstall version 3.8 python.

![image](https://github.com/nihaomiao/CVPR23_LFDM/assets/127167436/dc3001ff-44c5-47e4-9257-4a34b61988e4)

**Comment by TousenKaname** [comment]
Hi! I encounter this issue too. Do you solve this problem? Thanks!
