### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by SPengLiang** [nihaomiao/CVPR2023_LFDM#27]
Hi, thanks for your great work! How can I evaluate the test results? I did not find scripts/codes for quantitative evaluation for mhad dataset.

**Comment by nihaomiao** [comment]
Hi, @SPengLiang, thanks for your interest in our work! I use the FVD code provided [here](https://github.com/universome/fvd-comparison/blob/5b88a524a54ba5d685014ed4b35d75148fb66c28/compare_metrics.py#L32) to evaluate our models. You need to generate a number of fake videos first and then compare their distribution with that of real videos. The subject FVD and class FVD are just simple variants of the FVD score. You may check our paper for more details.

**Comment by SPengLiang** [comment]
@nihaomiao  Thanks a lot!

**Comment by SPengLiang** [comment]
@nihaomiao  Using this function (fvd = compute_our_fvd(model.real_out_vid.data.cpu().numpy().copy(), real_vids.data.cpu().numpy().copy())), I got an error: 
"RuntimeError: Given groups=1, weight of size [64, 3, 7, 7, 7], expected input[10, 128, 9, 45, 133] to have 3 channels, but got 128 channels instead ".  
The shapes of input videos are (10, 3, 40, 128, 128) and (10, 3, 40, 128, 128). Do I miss something?
