### ISSUE TITLE
torch.hub.load error

### ISSUE THREAD

**Issue by chenbolin-master** [nihaomiao/CVPR2023_LFDM#29]
TOKENIZER = torch.hub.load('huggingface/pytorch-transformers', 'tokenizer', 'bert-base-cased')   meet errors :

 File "/usr/lib/python3.8/importlib/metadata.py", line 169, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: regex

  File "/root/.cache/torch/hub/huggingface_pytorch-transformers_main/src/transformers/utils/versions.py", line 104, in require_version
    raise importlib.metadata.PackageNotFoundError(
importlib.metadata.PackageNotFoundError: The 'regex!=2019.12.17' distribution was not found and is required by this application.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

**Comment by chenbolin-master** [comment]
TOKENIZER = torch.hub.load('huggingface/pytorch-transformers', 'tokenizer', 'bert-base-cased')
MODEL = torch.hub.load('huggingface/pytorch-transformers', 'model', 'bert-base-cased')

how to download them by url ? 
My network can not download  by torch.hub.load .

**Comment by LargeRaindrop** [comment]
> TOKENIZER = torch.hub.load('huggingface/pytorch-transformers', 'tokenizer', 'bert-base-cased') meet errors :
> 
> File "/usr/lib/python3.8/importlib/metadata.py", line 169, in from_name raise PackageNotFoundError(name) importlib.metadata.PackageNotFoundError: regex
> 
> File "/root/.cache/torch/hub/huggingface_pytorch-transformers_main/src/transformers/utils/versions.py", line 104, in require_version raise importlib.metadata.PackageNotFoundError( importlib.metadata.PackageNotFoundError: The 'regex!=2019.12.17' distribution was not found and is required by this application. Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

I have encountered the same problem as you. Just use `pip install transformers -U` to update the package transformers.
