### ISSUE TITLE
cFVD and sFVD?

### ISSUE THREAD

**Issue by jacob-kang** [nihaomiao/CVPR2023_LFDM#3]
Thanks for your great work.

I saw your paper, and I want to enquire what is difference between cFVD,sFVD and normal FVD.
And where can I find cFVD, sFVD metric code?

Thanks.

**Comment by nihaomiao** [comment]
Hi, @jacob-kang, cFVD and sFVD can be easily computed based on normal FVD. For example, if you have 10 classes, you can first generate 10,000 videos for each class and then compute FVD for each class. The final cFVD will be the mean and std of these 10 FVD scores. The computation of sFVD is also similar. Just compute FVD for each subject and report the mean and std as the final sFVD score.

**Comment by jacob-kang** [comment]
Oh I got it. Thanks.
I close this issue.
