### ISSUE TITLE
doubts about the model name in the code

### ISSUE THREAD

**Issue by forever208** [nihaomiao/CVPR2023_LFDM#34]
Hi @nihaomiao, thanks for open-sourcing the awesome work!

I have a few doubts about the model names in the code.

In the script `run_natops.py`, what do `Generator`, `RegionPredictor` and `BGMotionPredictor` mean and are used for?
I am a bit confused because you denote the models as `encoder`, `decoder` and `flow predictor` in your paper.
So, what are the correspondences of them?

**Comment by nihaomiao** [comment]
Hi, @forever208, our generator is based on the [MRAA](https://github.com/snap-research/articulated-animation). You may refer to their paper and code for the role of these modules.
