### ISSUE TITLE
Why is the grid generated well in the demo file, but the grid generated in the train_video_flow_diffusion_mhad_multiGPU file is distorted?

### ISSUE THREAD

**Issue by Foxerity** [nihaomiao/CVPR2023_LFDM#35]
the grid generated well in the demo file
![200_0000_a11_s4_t1_000_1 00](https://github.com/nihaomiao/CVPR23_LFDM/assets/55437654/f64e10ae-7c68-4291-8904-9b9c2c17ac12)
the grid generated in the train_video_flow_diffusion_mhad_multiGPU file
![B0010_S000000_a8_s1_t3_0](https://github.com/nihaomiao/CVPR23_LFDM/assets/55437654/2be19ae4-9422-40fb-9f0a-369ad1686b8a)
I am referring to the GT grid. The grid in the demo is square, but in the file below is folded. I'm using the same AE weights.

**Comment by Foxerity** [comment]
I mean the grid in the first row of the picture below. I know the lower row is because it is not trained well.

**Comment by nihaomiao** [comment]
Hi, @Foxerity, have you loaded the correct pre-trained stage-one latent autoencoder? The ground truth flow should not have any issues.
