### ISSUE TITLE
FVD calculation

### ISSUE THREAD

**Issue by take323** [nihaomiao/CVPR2023_LFDM#36]
Thanks for your work!

I used the pretrained models published in this repository and calculated the FVD using [this repository](https://github.com/universome/stylegan-v).
However, I obtained FVDs much larger than those in the paper.
Could you please release the source code for calculating FVD?

**Comment by HARVEYDOU** [comment]
same question

**Comment by nihaomiao** [comment]
Hi, @take323 @HARVEYDOU , thanks a lot for your interest in our work! I think I use the same code as the repo you mentioned. But FVD depends on many factors, such as the number of videos (we use 10,000), the resolution, number of frames, and sample rate (we sample 40 frames with the resolution of 128*128 from the ground truth video), etc. Using different settings may result in different FVD scores.
