### ISSUE TITLE
What do the "deformed" and "prediction" mean?

### ISSUE THREAD

**Issue by HARVEYDOU** [nihaomiao/CVPR2023_LFDM#39]
HI!
![1700363922222](https://github.com/nihaomiao/CVPR23_LFDM/assets/45869268/a5fdc22c-19e0-4e99-9ff4-d976842efca4)
In codes:
real_out_img_list.append(generated["prediction"])
real_warped_img_list.append(generated["deformed"])
![1700363554920](https://github.com/nihaomiao/CVPR23_LFDM/assets/45869268/cd09ecf7-fc94-4eb0-a152-926890fd98c5)
In the demo, what do the second and the third part seperately mean? As i know, they are probably "deformed" and "prediction". Could you describe it in detail.
Appreciate for your patient answer

**Comment by nihaomiao** [comment]
"deformed" means directly applying the optical flow (deformation flow) to the original image to show the warped result, while "prediction" represents the final output image from the decoder of our network.

**Comment by HARVEYDOU** [comment]
Thanks a lot!

**Comment by HARVEYDOU** [comment]
Thanks a lot!

> "deformed" means directly applying the optical flow (deformation flow) to the original image to show the warped result, while "prediction" represents the final output image from the decoder of our network.
