### ISSUE TITLE
KeyError: 'bottle_neck_feat'

### ISSUE THREAD

**Issue by Yueming6568** [nihaomiao/CVPR2023_LFDM#4]
Thank you for your excellent work ! I have a problem below.

When I am trying to train DM model and running "python -u DM/train_video_flow_diffusion_mhad.py"， there is an error below:
File "CVPR23_LFDM/DM/modules/video_flow_diffusion_model.py", line 144, in forward
    self.ref_img_fea = generated["bottle_neck_feat"].clone().detach()
KeyError: 'bottle_neck_feat' 

I cannot find the key ''bottle_neck_feat'' in the generator.py, please help me to solve it ~ Thank you very much!

**Comment by nihaomiao** [comment]
Hi, @Yueming6568, thanks for your comments! I have fixed the bug. Please feel free to let me know if you find other problems.

**Comment by Yueming6568** [comment]
Sure : ) Thank you for your kind reply ! 👍
