### ISSUE TITLE
What do fake and real graphs refer to?

### ISSUE THREAD

**Issue by HARVEYDOU** [nihaomiao/CVPR2023_LFDM#40]
![1702622070466](https://github.com/nihaomiao/CVPR23_LFDM/assets/45869268/065fc243-cca7-40c2-9c11-896624b0cb37)
I have troble understanding what does these respertively  means.
Grateful to get your response.

**Comment by nihaomiao** [comment]
Hi, @HARVEYDOU, thanks a lot for your interest in our work! `save_real_out_img` means the ground truth image; `save_real_warp_img` is generated by applying the pseudo ground truth flow to the reference image; `save_fake_out_img` means the predicted image; `save_fake_warp_img` is generated by applying the synthesized flow to the reference images.
