### ISSUE TITLE
Inquiries about face occlusion map

### ISSUE THREAD

**Issue by yitiaolittle** [nihaomiao/CVPR2023_LFDM#41]
Hi，Thanks for your great work！
Here are a few questions for you to answer!
Why is the dark area of the face mainly the eyes, mouth, and edge contours of the face? 
Is there the most occlusion here? Does eye occlusion mean that the eyes may be closed? Does the occlusion of the mouth mean that there may be teeth? I don't know if I understand it right? So why do the edge contours shade so deeply? What needs to be redrawn there?

![625b845ad20f82c7615e0c6f0464e05](https://github.com/nihaomiao/CVPR23_LFDM/assets/105427014/8385c1fc-beeb-4ffd-a2ea-b183a20abce0)
![094b2443da8ac2f480bbe80fc3b1a6b](https://github.com/nihaomiao/CVPR23_LFDM/assets/105427014/1b033c98-0b14-4eeb-989e-088f6dc10204)

**Comment by nihaomiao** [comment]
Hi, @yitiaolittle, thanks a lot for your interest in our work! The values in the occlusion map change from 0 to 1. 0 is dark and will fully mask the corresponding pixels and 1 is bright/white and will fully keep the pixel. Your understanding of eye and mouth regions should be correct.  For the edge areas, I guess that the model predictions are unstable in these regions so the generated occlusion maps tend to mask them.

**Comment by yitiaolittle** [comment]
> Hi, @yitiaolittle, thanks a lot for your interest in our work! The values in the occlusion map change from 0 to 1. 0 is dark and will fully mask the corresponding pixels and 1 is bright/white and will fully keep the pixel. Your understanding of eye and mouth regions should be correct. For the edge areas, I guess that the model predictions are unstable in these regions so the generated occlusion maps tend to mask them.
Thank you very much!!
