### ISSUE TITLE
demo_mug.py RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB V100 32G

### ISSUE THREAD

**Issue by Zenobia7** [nihaomiao/CVPR2023_LFDM#42]
Hello, I have a memory leak in the test, in the diffusion 1000 iterations when the memory rose from 14G to 32G so that can not be tested, please help to see what is the reason? python3.7.10 pytorch1.12.1+cu10.2 is installed in requirements.txt for all environments.
![微信图片_20240124094820](https://github.com/nihaomiao/CVPR23_LFDM/assets/28126038/43f4667e-7cd8-4ac9-8c33-ee293983fb11)
![微信图片_20240124094816](https://github.com/nihaomiao/CVPR23_LFDM/assets/28126038/eae89ffa-0641-48b1-9d42-56ea97e9492d)
![微信图片_20240124094812](https://github.com/nihaomiao/CVPR23_LFDM/assets/28126038/dd45184c-2682-480d-817b-2d612d249909)
![微信图片_20240124094809](https://github.com/nihaomiao/CVPR23_LFDM/assets/28126038/1dcbe3ff-a3da-4cc8-b4a8-827ed8f6f2c4)
![微信图片_20240124094806](https://github.com/nihaomiao/CVPR23_LFDM/assets/28126038/1f4258f6-86a9-490b-9661-e9e41a34ad9c)
![微信图片_20240124094756](https://github.com/nihaomiao/CVPR23_LFDM/assets/28126038/1198b7e9-764a-413c-902a-a82bbc656d5c)

**Comment by nihaomiao** [comment]
Hi, @Zenobia7, sorry for the late reply! But I do not have such an issue before and normally the memory of the program will not be more than 24G.
