### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by geniussu0424** [nihaomiao/CVPR2023_LFDM#43]
可以分享一下MUG数据集吗，我去官网发的邮件没有回复。
Can you share the MUG data set, I went to the official website and sent an email without a reply.

**Comment by nihaomiao** [comment]
HI, @geniussu0424, the owner of the MUG dataset doesn't allow others to redistribute their data. You may need to wait for their reply or contact someone in their group.

**Comment by Chendaiping** [comment]
> 可以分享一下MUG数据集吗，我去官网发的邮件没有回复。 Can you share the MUG data set, I went to the official website and sent an email without a reply.

Hello, I have the same issue. May I ask if you were able to successfully obtain the dataset? Have you found the contact information of other lab members and managed to get it?
