### ISSUE TITLE
'jitter' effect

### ISSUE THREAD

**Issue by h-bouzid** [nihaomiao/CVPR2023_LFDM#45]
Hi dear @nihaomiao 

Congratulations on your very interesting work! I'm curious about the role of data jittering. If it's to prevent model overfitting, why was it implemented only in the DM and not in the LFAE? and have you tested running the DM without jittering the data? 

Thank you in advance 😁

**Comment by nihaomiao** [comment]
Hi, @h-bouzid, thanks a lot for your interest in our work! To be honest, I have not noticed this point before. But LFAE is initialized with a pretrained model. It would be OK without using "jitter". I have not tested training the DM without using "jitter". In general, data augmentation should not have negative effects.

**Comment by h-bouzid** [comment]
Thank you for your answer @nihaomiao.
