### ISSUE TITLE
KeyError: 'photometric'

### ISSUE THREAD

**Issue by Yueming6568** [nihaomiao/CVPR2023_LFDM#5]
Hi, haomiao. When I run "python -u LFAE/run_mhad.py" to train the LFAE model, I have the bug :
File "CVPR23_LFDM/LFAE/modules/model.py", line 217, in forward
    if self.loss_weights['photometric'] != 0:
KeyError: 'photometric'

May be the loss_weights of 'photometric' should be provided in config/xxx128.yaml . Looking forward to your reply : )

**Comment by nihaomiao** [comment]
Hi, @Yueming6568, thanks a lot for letting me know! I have fixed the bug. The "photometric" loss is useless. I have deleted some useless codes in model.py. You can try it again. Please feel free to let me know if you find any other problems.

**Comment by Yueming6568** [comment]
Thank you a lot for your reply ! The LFAE  model can be trained now !
