### ISSUE TITLE
Requirements file before running a demo ?

### ISSUE THREAD

**Issue by arunsank** [nihaomiao/CVPR2023_LFDM#6]
Is there a requirements file to install dependencies before running the demo ?

**Comment by nihaomiao** [comment]
Hi, @arunsank, I don't particularly prepare the requirements file for this project. But I try to use pipreqs to generate one and have uploaded it to this repo [link](https://github.com/nihaomiao/CVPR23_LFDM/blob/9cc0e102cb3253d72c5fb155613f5dc3846ae64a/requirements.txt). Hope it can help!

**Comment by arunsank** [comment]
Thank you for the quick response !

**Comment by RemaDaher** [comment]
hello thank you for this repo. regarding "requirements.py" pytorch-transformers are not included. is there a specific way you installed them?

**Comment by nihaomiao** [comment]
Hi, @RemaDaher, according to this [code](https://github.com/nihaomiao/CVPR23_LFDM/blob/9cc0e102cb3253d72c5fb155613f5dc3846ae64a/DM/modules/text.py#L19), I think the program will install/download them if it doesn't detect them?  BTW, the code of this part is from [video diffusion models](https://github.com/lucidrains/video-diffusion-pytorch). Its requirements may also help you.
