### ISSUE TITLE
Demo for NATOPS Dataset

### ISSUE THREAD

**Issue by Michel-liu** [nihaomiao/CVPR2023_LFDM#8]
I only find the demo files for MHAD and MUG in the `demo` folder. Will be the demo of NATOPS publicly available?

**Comment by nihaomiao** [comment]
Hi, @Michel-liu, thanks for your interest in our work! I am busy with some projects now but I can release the demo of NATOPS at the end of this month. The part of this code is very similar to the demo of MUG and MHAD. So you can also use my released pre-trained model and the NATOPS dataset to run a demo if you need it right now. I will also let you know after I release the demo of NATOPS.

**Comment by nihaomiao** [comment]
Hi, @Michel-liu, I have released the demo of the NATOPS dataset. I also update the link to the pre-trained DM model of the NATOPS dataset. You may need to download this latest model for the demo. Please feel free to let me know if you have any other questions.

**Comment by Michel-liu** [comment]
Nice! Thanks! 😄
