### ISSUE TITLE
Which version of 'Pillow' package should we use?

### ISSUE THREAD

**Issue by Lanhaoran** [nihaomiao/CVPR2023_LFDM#9]
When I was creating the environment, I ran into an error:
`ERROR: Cannot install Pillow==9.2.0 and Pillow==9.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Pillow==9.2.0
    The user requested Pillow==9.5.0`

and I noticed there are two different version of pillow in the requirements.txt, so which one is the correct version? Thanks!

**Comment by nihaomiao** [comment]
Hi, @Lanhaoran, thanks a lot for your interest! I think it should be 9.2.0. I have updated the file "requirements.txt". Please feel free to let me know if you have any questions.

**Comment by Lanhaoran** [comment]
> Hi, @Lanhaoran, thanks a lot for your interest! I think it should be 9.2.0. I have updated the file "requirements.txt". Please feel free to let me know if you have any questions.

It helps a lot! Thanks!
